START TRANSACTION;

CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(255) NOT NULL,password VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL,role VARCHAR(255) NOT NULL)

CREATE TABLE IF NOT EXISTS questions (id INT PRIMARY KEY AUTO_INCREMENT,question VARCHAR(1024) NOT NULL,a VARCHAR(255) NOT NULL,b VARCHAR(255) NOT NULL,c VARCHAR(255) NOT NULL,d VARCHAR(255) NOT NULL,correct VARCHAR(255) NOT NULL,image VARCHAR(2048) NOT NULL,image_fallback VARCHAR(2048) NOT NULL)

COMMIT;

